# Generated by Django 2.1.4 on 2018-12-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('studentid', models.IntegerField(max_length=8)),
                ('email', models.CharField(max_length=50)),
                ('password', models.IntegerField(max_length=20)),
            ],
        ),
    ]
