# Generated by Django 2.1.4 on 2018-12-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181227_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='admin',
            name='lastindex',
            field=models.IntegerField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
