# Generated by Django 2.1.4 on 2018-12-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181227_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admin',
            name='lastindex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentid',
            field=models.IntegerField(default=0),
        ),
    ]
