# Generated by Django 2.1.4 on 2018-12-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181227_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='cnt',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='studentid',
            field=models.CharField(max_length=10),
        ),
    ]
